# Generated by Django 3.1.6 on 2021-02-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreDrDra', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('asignatura', models.CharField(max_length=50)),
                ('ciclo', models.CharField(max_length=30)),
                ('carrera', models.CharField(max_length=100)),
            ],
        ),
    ]
